CREATE TABLE IF NOT EXISTS category_catalog (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  universe TEXT NOT NULL CHECK (universe IN ('MARKET','SAVEURS','EVASION')),
  slug TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  icon TEXT NOT NULL DEFAULT '•',
  parent_slug TEXT,
  sort_order INTEGER NOT NULL DEFAULT 0,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  filters JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (universe, slug)
);

CREATE INDEX IF NOT EXISTS idx_category_catalog_universe_order
  ON category_catalog(universe, active, sort_order, name);
CREATE INDEX IF NOT EXISTS idx_category_catalog_parent
  ON category_catalog(universe, parent_slug, sort_order);

INSERT INTO category_catalog (universe, slug, name, description, icon, sort_order, filters) VALUES
('MARKET','mode','Mode & Vêtements','Vêtements, chaussures et style pour toute la famille.','👕',10,'{"gender":["Femme","Homme","Enfant"],"size":["XS","S","M","L","XL","XXL"],"condition":["Neuf","Seconde main"]}'),
('MARKET','telephones-accessoires','Téléphones & Accessoires','Smartphones, téléphones et accessoires mobiles.','📱',20,'{"brand":[],"condition":["Neuf","Seconde main"],"price":true}'),
('MARKET','informatique-electronique','Informatique & Électronique','Ordinateurs, tablettes, audio et équipements électroniques.','💻',30,'{"brand":[],"condition":["Neuf","Seconde main"],"price":true}'),
('MARKET','maison-decoration','Maison & Décoration','Mobilier, décoration, rangement et équipement de la maison.','🏠',40,'{"room":["Salon","Chambre","Cuisine","Salle de bain","Bureau"],"condition":["Neuf","Seconde main"]}'),
('MARKET','electromenager','Électroménager','Gros et petit électroménager.','🧊',50,'{"energy_class":[],"condition":["Neuf","Seconde main"],"price":true}'),
('MARKET','beaute-soins','Beauté & Soins','Parfums, maquillage, cheveux et soins.','💄',60,'{"gender":["Femme","Homme","Unisexe"],"skin_type":[],"hair_type":[]}'),
('MARKET','bebe-enfant','Bébé & Enfant','Mode, jouets et articles de puériculture.','🧸',70,'{"age":["0-3 mois","3-12 mois","1-3 ans","3-6 ans","6-12 ans","12+"],"gender":["Fille","Garçon","Mixte"]}'),
('MARKET','sports-loisirs','Sports & Loisirs','Sport, fitness, jeux et loisirs.','⚽',80,'{"sport":[],"gender":["Femme","Homme","Enfant"],"condition":["Neuf","Seconde main"]}'),
('MARKET','alimentation-epicerie','Alimentation & Épicerie','Produits alimentaires et épicerie du quotidien.','🛒',90,'{"diet":["Classique","Halal","Bio"],"fresh":true}'),
('MARKET','supermarche-quotidien','Supermarché & Quotidien','Hygiène, entretien et consommables du quotidien.','🧴',100,'{"brand":[],"price":true}'),
('MARKET','accessoires-maroquinerie','Accessoires & Maroquinerie','Sacs, montres, bijoux, lunettes et accessoires.','👜',110,'{"gender":["Femme","Homme","Unisexe"],"material":[]}'),
('MARKET','auto-moto','Auto & Moto','Accessoires, entretien et équipements automobiles et moto.','🚗',120,'{"vehicle":[],"brand":[],"condition":["Neuf","Occasion"]}'),
('MARKET','bricolage-jardin','Bricolage & Jardin','Outils, équipements, jardinage et entretien.','🔧',130,'{"type":[],"condition":["Neuf","Occasion"]}'),
('MARKET','bureau-fournitures','Bureau & Fournitures','Papeterie, fournitures scolaires et matériel de bureau.','📚',140,'{"audience":["Scolaire","Étudiant","Professionnel"]}'),
('MARKET','livres-culture-education','Livres, Culture & Éducation','Livres, supports éducatifs et produits culturels.','📖',150,'{"language":["Français","Anglais","Autre"],"condition":["Neuf","Occasion"]}'),
('MARKET','produits-locaux-artisanat','Produits locaux & Artisanat','Créations locales, artisanat et produits faits main.','🧺',160,'{"origin":["Sénégal","Afrique","International"],"handmade":true}'),
('MARKET','services','Services','Services professionnels, à domicile et événementiels.','🛠️',170,'{"city":[],"availability":[]}'),

('SAVEURS','restaurants','Restaurants','Restaurants et cuisines disponibles à la commande.','🍽️',10,'{"cuisine":[],"open_now":true,"delivery":true,"takeaway":true,"halal":true,"vegetarian":true}'),
('SAVEURS','plats-senegalais','Plats sénégalais','Les grands classiques de la cuisine sénégalaise.','🍲',20,'{"spice":["Doux","Moyen","Épicé"],"portion":["Individuelle","Famille"]}'),
('SAVEURS','fast-food','Fast-Food','Burgers, tacos, shawarma, pizzas et poulet.','🍔',30,'{"cuisine":[],"delivery":true,"takeaway":true,"open_now":true}'),
('SAVEURS','petit-dejeuner-brunch','Petit-déjeuner & Brunch','Petit-déjeuner, brunch, viennoiseries et crêpes.','🥐',40,'{"meal_time":["Matin","Brunch"],"delivery":true}'),
('SAVEURS','boissons','Boissons','Jus, boissons fraîches, café et thé.','🥤',50,'{"temperature":["Froid","Chaud"],"natural":true}'),
('SAVEURS','desserts-patisseries','Desserts & Pâtisseries','Gâteaux, glaces, pâtisseries et desserts.','🍰',60,'{"occasion":["Anniversaire","Mariage","Quotidien"],"custom":true}'),
('SAVEURS','epicerie','Épicerie','Produits d’épicerie et essentiels alimentaires.','🛍️',70,'{"fresh":false,"halal":true,"organic":true}'),
('SAVEURS','fruits-legumes','Fruits & Légumes','Produits frais et paniers de saison.','🥬',80,'{"seasonal":true,"organic":true}'),
('SAVEURS','boucherie-poissonnerie','Boucherie & Poissonnerie','Viandes, volailles, poissons et fruits de mer.','🐟',90,'{"fresh":true,"delivery":true}'),
('SAVEURS','traiteur-evenementiel','Traiteur & Événementiel','Buffets et prestations pour événements.','🎉',100,'{"event":["Mariage","Baptême","Anniversaire","Entreprise"],"quote":true}'),
('SAVEURS','cuisine-maison','Cuisine maison','Plats et produits préparés par des partenaires locaux.','🏡',110,'{"homemade":true,"delivery":true}'),
('SAVEURS','offres-menus','Offres & Menus','Menus du jour, formules, packs et promotions.','🏷️',120,'{"promotion":true,"family":true,"delivery":true}'),

('EVASION','hotels','Hôtels','Hôtels pour courts et longs séjours.','🏨',10,'{"stars":[1,2,3,4,5],"pool":true,"wifi":true,"breakfast":true,"air_conditioning":true}'),
('EVASION','locations','Appartements & Locations','Appartements, villas, maisons et studios.','🏡',20,'{"guests":[],"rooms":[],"pool":true,"wifi":true}'),
('EVASION','residences-maisons-hotes','Résidences & Maisons d’hôtes','Résidences, lodges, auberges et maisons d’hôtes.','🛖',30,'{"breakfast":true,"wifi":true,"family":true}'),
('EVASION','plages-resorts','Plages & Resorts','Séjours balnéaires, piscines et beach clubs.','🏝️',40,'{"pool":true,"beach_access":true,"family":true}'),
('EVASION','excursions','Excursions','Excursions à la journée, circuits et visites guidées.','🚌',50,'{"duration":[],"group_size":[],"guide":true}'),
('EVASION','activites-experiences','Activités & Expériences','Loisirs, sport, découverte et expériences locales.','🎟️',60,'{"difficulty":["Facile","Intermédiaire","Sportif"],"duration":[],"family":true}'),
('EVASION','tourisme-culture','Tourisme & Culture','Patrimoine, musées, monuments et expériences culturelles.','🏛️',70,'{"language":[],"guide":true,"family":true}'),
('EVASION','restaurants-gastronomie','Restaurants & Gastronomie','Expériences culinaires et restaurants touristiques.','🍴',80,'{"cuisine":[],"reservation":true,"halal":true,"vegetarian":true}'),
('EVASION','transport-mobilite','Transport & Mobilité','Location, chauffeurs et transferts.','🚗',90,'{"vehicle":[],"driver":true,"airport_transfer":true}'),
('EVASION','billetterie-evenements','Billetterie & Événements','Concerts, festivals, spectacles et événements.','🎫',100,'{"event_type":[],"date":true,"venue":[]}'),
('EVASION','voyages-organises','Voyages organisés','Circuits, packages et voyages accompagnés.','🗺️',110,'{"destination":[],"duration":[],"group_size":[]}'),
('EVASION','lune-de-miel-romantique','Lune de miel & Romantique','Séjours et expériences pour couples.','❤️',120,'{"couple":true,"private":true,"romantic":true}'),
('EVASION','famille','Famille','Séjours et activités adaptés aux familles.','👨‍👩‍👧‍👦',130,'{"children":true,"family":true,"age":[]}'),
('EVASION','business-seminaires','Business & Séminaires','Hôtels, salles, réunions et team building.','💼',140,'{"meeting_room":true,"wifi":true,"capacity":[]}'),
('EVASION','bien-etre','Bien-être','Spas, massages, hammam, yoga et détente.','🧘',150,'{"couple":true,"appointment":true}'),
('EVASION','destinations','Destinations','Explorer les destinations du Sénégal, de la sous-région et de l’international.','🌍',160,'{"country":[],"city":[],"region":[]}')
ON CONFLICT (universe, slug) DO UPDATE SET
  name=EXCLUDED.name,
  description=EXCLUDED.description,
  icon=EXCLUDED.icon,
  sort_order=EXCLUDED.sort_order,
  filters=EXCLUDED.filters,
  updated_at=NOW();

INSERT INTO category_catalog (universe, slug, name, description, parent_slug, sort_order) VALUES
('MARKET','mode-femme','Femme','Mode femme.','mode',11),
('MARKET','mode-homme','Homme','Mode homme.','mode',12),
('MARKET','mode-enfant','Enfant','Mode enfant.','mode',13),
('MARKET','mode-chaussures','Chaussures','Chaussures et sneakers.','mode',14),
('MARKET','mode-traditionnel','Vêtements traditionnels','Tenues traditionnelles et cérémonie.','mode',15),
('MARKET','mode-sport','Sport & Fitness','Tenues et équipements de sport.','mode',16),
('MARKET','telephones-smartphones','Smartphones','Smartphones et téléphones.','telephones-accessoires',21),
('MARKET','telephones-coques','Coques & Protections','Protection mobile.','telephones-accessoires',22),
('MARKET','telephones-chargeurs','Chargeurs & Câbles','Chargeurs, câbles et adaptateurs.','telephones-accessoires',23),
('MARKET','telephones-audio','Écouteurs & Casques','Audio mobile.','telephones-accessoires',24),
('MARKET','telephones-powerbanks','Power banks','Batteries externes.','telephones-accessoires',25),
('MARKET','informatique-ordinateurs','Ordinateurs','PC portables et fixes.','informatique-electronique',31),
('MARKET','informatique-tablettes','Tablettes','Tablettes et accessoires.','informatique-electronique',32),
('MARKET','informatique-imprimantes','Imprimantes','Imprimantes et consommables.','informatique-electronique',33),
('MARKET','informatique-accessoires','Accessoires informatiques','Claviers, souris, webcams et autres.','informatique-electronique',34),
('MARKET','maison-meubles','Meubles','Mobilier intérieur et extérieur.','maison-decoration',41),
('MARKET','maison-decoration','Décoration','Objets et accessoires déco.','maison-decoration',42),
('MARKET','maison-literie','Literie','Matelas, draps et linge de maison.','maison-decoration',43),
('MARKET','maison-cuisine','Cuisine','Ustensiles et équipement cuisine.','maison-decoration',44),
('MARKET','maison-eclairage','Éclairage','Lampes et luminaires.','maison-decoration',45),
('MARKET','beaute-parfums','Parfums','Parfums et fragrances.','beaute-soins',61),
('MARKET','beaute-maquillage','Maquillage','Maquillage et accessoires.','beaute-soins',62),
('MARKET','beaute-visage','Soins visage','Soins et routines visage.','beaute-soins',63),
('MARKET','beaute-cheveux','Cheveux','Soins, coiffure et accessoires cheveux.','beaute-soins',64),
('MARKET','accessoires-sacs','Sacs','Sacs et bagagerie.','accessoires-maroquinerie',111),
('MARKET','accessoires-montres','Montres','Montres et accessoires.','accessoires-maroquinerie',112),
('MARKET','accessoires-bijoux','Bijoux','Bijoux et accessoires.','accessoires-maroquinerie',113),
('MARKET','accessoires-lunettes','Lunettes','Lunettes et accessoires.','accessoires-maroquinerie',114),
('SAVEURS','plats-thieboudienne','Thiéboudienne','Le plat emblématique du Sénégal.','plats-senegalais',21),
('SAVEURS','plats-yassa','Yassa','Yassa poulet, poisson et variantes.','plats-senegalais',22),
('SAVEURS','plats-mafe','Mafé','Mafé et variantes.','plats-senegalais',23),
('SAVEURS','plats-ceebu-yapp','Ceebu yapp','Riz à la viande.','plats-senegalais',24),
('SAVEURS','plats-soupou-kandia','Soupou kandia','Cuisine traditionnelle.','plats-senegalais',25),
('SAVEURS','fastfood-burgers','Burgers','Burgers et menus.','fast-food',31),
('SAVEURS','fastfood-tacos','Tacos','Tacos et formules.','fast-food',32),
('SAVEURS','fastfood-pizza','Pizzas','Pizzas et formules.','fast-food',33),
('SAVEURS','boissons-jus','Jus naturels','Jus, bissap, bouye et gingembre.','boissons',51),
('SAVEURS','boissons-cafe-the','Café & Thé','Boissons chaudes.','boissons',52),
('SAVEURS','desserts-gateaux','Gâteaux','Gâteaux personnalisés et classiques.','desserts-patisseries',61),
('SAVEURS','desserts-glaces','Glaces','Glaces et desserts glacés.','desserts-patisseries',62),
('SAVEURS','traiteur-mariage','Mariage','Traiteur mariage.','traiteur-evenementiel',101),
('SAVEURS','traiteur-bapteme','Baptême','Traiteur baptême.','traiteur-evenementiel',102),
('SAVEURS','traiteur-entreprise','Entreprise','Traiteur entreprise et séminaires.','traiteur-evenementiel',103),
('EVASION','hotels-luxe','Hôtels de luxe','Hôtels 4 et 5 étoiles.','hotels',11),
('EVASION','hotels-economiques','Hôtels économiques','Hébergements à budget maîtrisé.','hotels',12),
('EVASION','hotels-resorts','Resorts','Resorts et grands complexes.','hotels',13),
('EVASION','locations-appartements','Appartements','Appartements courte durée.','locations',21),
('EVASION','locations-villas','Villas','Villas et maisons.','locations',22),
('EVASION','excursions-journee','Excursions à la journée','Sorties sur une journée.','excursions',51),
('EVASION','excursions-circuits','Circuits','Circuits guidés.','excursions',52),
('EVASION','activites-sport','Sport & Aventure','Surf, quad, kayak, randonnée et autres.','activites-experiences',61),
('EVASION','activites-culture','Culture & Découverte','Visites et expériences locales.','activites-experiences',62),
('EVASION','transport-location','Location de voiture','Location de véhicules.','transport-mobilite',91),
('EVASION','transport-chauffeur','Chauffeur privé','Chauffeurs et transferts privés.','transport-mobilite',92),
('EVASION','transport-aeroport','Transfert aéroport','Transferts depuis et vers les aéroports.','transport-mobilite',93),
('EVASION','destinations-senegal','Sénégal','Dakar, Saly, Gorée, Saint-Louis, Casamance et autres.','destinations',161),
('EVASION','destinations-sous-region','Sous-région','Afrique de l’Ouest et destinations voisines.','destinations',162),
('EVASION','destinations-international','International','Destinations internationales.','destinations',163)
ON CONFLICT (universe, slug) DO UPDATE SET
  name=EXCLUDED.name,
  description=EXCLUDED.description,
  parent_slug=EXCLUDED.parent_slug,
  sort_order=EXCLUDED.sort_order,
  updated_at=NOW();
