const API = "/api";
let products = [], category = "", searchMode = "classic", aiQueryText = "";
const DEMO_PRODUCTS = [
  {id:"demo-tee",name:"T-shirt qualité premium",category:"Mode",description:"T-shirt confortable et élégant.",price_fcfa:10000,stock:20,image_url:"https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80",verified_level:"VERIFIED",verification_score:78,rating_average:4.8,rating_count:14},
  {id:"demo-satchel",name:"Sac Élégance",category:"Accessoires",description:"Sac moderne et élégant pour le quotidien.",price_fcfa:18000,stock:12,image_url:"https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=900&q=80",verified_level:"VERIFIED",verification_score:72,rating_average:4.5,rating_count:8},
  {id:"demo-watch",name:"Montre classique",category:"Mode",description:"Montre au design intemporel.",price_fcfa:25000,stock:8,image_url:"https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80",verified_level:"STANDARD",verification_score:54,rating_average:4.1,rating_count:3}
];
const lang=()=>window.EgonarI18n?.getLang?.()||localStorage.getItem("egonar_language")||"fr";
const tr=(fr,en)=>lang()==="en"?en:fr;
const money=n=>new Intl.NumberFormat("fr-FR").format(Number(n)||0)+" FCFA";
const cart=()=>{try{return JSON.parse(localStorage.getItem("egonarCart")||"[]")}catch{return[]}};
const saveCart=c=>{localStorage.setItem("egonarCart",JSON.stringify(c));updateCount()};
const updateCount=()=>{const e=document.getElementById("cart-count");if(e)e.textContent=cart().reduce((s,x)=>s+Number(x.quantity||0),0)};
const esc=s=>String(s??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const normalize=s=>String(s||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"");
async function api(path,options={}){const r=await fetch(API+path,options),data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||tr("Une erreur est survenue.","Something went wrong."));return data}
function siteEnhancements(){const nav=document.querySelector("header nav");if(nav){[["food.html","🍽️ Saveurs"],["travel.html","✈️ Évasion"]].forEach(([href,label])=>{if(!nav.querySelector(`a[href="${href}"]`)){const a=document.createElement("a");a.href=href;a.textContent=label;nav.insertBefore(a,nav.firstChild)}})}const chips=document.querySelector(".chips");if(chips&&!chips.querySelector('[data-category="Bébés & Enfants"]')){const b=document.createElement("button");b.type="button";b.className="chip";b.dataset.category="Bébés & Enfants";b.textContent=tr("Bébés & Enfants","Baby & Kids");b.onclick=()=>{chips.querySelectorAll("[data-category]").forEach(x=>x.classList.remove("active"));b.classList.add("active");category=b.dataset.category;searchMode="classic";load()};chips.appendChild(b)}}
function injectAiReasonStyles(){if(document.getElementById("egonar-ai-reasons-style"))return;const s=document.createElement("style");s.id="egonar-ai-reasons-style";s.textContent=`.ai-reason{margin:8px 0 10px;border:1px solid rgba(67,153,205,.18);border-radius:14px;background:#f7fbff;overflow:hidden}.ai-reason summary{list-style:none;cursor:pointer;padding:9px 11px;font-size:11px;font-weight:800;color:#135b91;display:flex;align-items:center;gap:7px}.ai-reason summary::-webkit-details-marker{display:none}.ai-reason summary:after{content:"+";margin-left:auto;font-size:16px}.ai-reason[open] summary:after{content:"−"}.ai-reason ul{margin:0;padding:0 12px 11px 28px;display:grid;gap:5px;color:#446071;font-size:11px;line-height:1.45}.ai-reason-badge{display:inline-flex;padding:4px 7px;border-radius:999px;background:#e8f6ff;color:#135b91;font-size:10px;font-weight:800}`;document.head.appendChild(s)}
function buildAiReasons(p){if(searchMode!=="ai")return"";const q=normalize(aiQueryText),reasons=[],price=Number(p.price_fcfa||0),budget=Number(p._ai_budget||0),rating=Number(p.rating_average||0),ratingCount=Number(p.rating_count||0),score=Number(p.verification_score||0),dmax=Number(p.delivery_max_minutes||0),dmin=Number(p.delivery_min_minutes||0),verified=["VERIFIED","PREMIUM"].includes(String(p.verified_level||"").toUpperCase());if(budget&&price<=budget)reasons.push(tr(`Respecte votre budget de ${money(budget)}.`,`Fits your ${money(budget)} budget.`));const words=q.split(/[^a-z0-9]+/).filter(w=>w.length>2).slice(0,8),hay=normalize(`${p.name||""} ${p.description||""} ${p.category||""} ${p.subcategory||""}`),matches=words.filter(w=>hay.includes(w)).slice(0,2);if(matches.length)reasons.push(tr(`Correspond à votre recherche : ${matches.join(", ")}.`,`Matches your search: ${matches.join(", ")}.`));if(verified)reasons.push(tr("Produit vérifié et contrôlé par Egonar.","Product verified and checked by Egonar."));if(rating>=4&&ratingCount)reasons.push(tr(`Note ${rating.toFixed(1)}/5 basée sur ${ratingCount} avis.`,`Rated ${rating.toFixed(1)}/5 from ${ratingCount} reviews.`));if(dmax)reasons.push(tr(`Livraison estimée ${dmin?`${dmin}–`:""}${dmax} min${p.delivery_city?` à ${p.delivery_city}`:""}.`,`Estimated delivery ${dmin?`${dmin}–`:""}${dmax} min${p.delivery_city?` in ${p.delivery_city}`:""}.`));if(score>=68&&reasons.length<4)reasons.push(tr(`Score de confiance Egonar : ${score}/100.`,`Egonar trust score: ${score}/100.`));if(!reasons.length)reasons.push(tr("Sélectionné pour sa pertinence globale par rapport à votre recherche.","Selected for overall relevance to your search."));return `<details class="ai-reason"><summary><span class="ai-reason-badge">✦ ${tr("Pourquoi recommandé","Why recommended")}</span></summary><ul>${reasons.slice(0,4).map(r=>`<li>${esc(r)}</li>`).join("")}</ul></details>`}
async function load(){const box=document.getElementById("products-list")||document.getElementById("products");if(box)box.innerHTML=`<div class="empty-state"><h3>${tr("Chargement…","Loading…")}</h3><p>${tr("Nous préparons votre sélection.","Preparing your selection.")}</p></div>`;try{const qs=category?`?category=${encodeURIComponent(category)}`:"",data=await api(`/products${qs}`);products=Array.isArray(data)?data:(data.products||[]);render()}catch(e){products=DEMO_PRODUCTS.slice();render();showToast(tr("Mode aperçu activé : le catalogue réel sera chargé dès que l’API est disponible.","Preview mode enabled: the live catalog will load when the API is available."))}updateCount()}
async function smartSearch(message){const text=String(message||"").trim();if(!text)return;aiQueryText=text;const box=document.getElementById("products-list")||document.getElementById("products");if(box)box.innerHTML=`<div class="empty-state"><h3>${tr("Recherche intelligente…","Smart search…")}</h3><p>${tr("Analyse de votre demande en cours.","Analyzing your request…")}</p></div>`;searchMode="ai";try{const data=await api("/ai/search",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:text,language:lang()})});products=(Array.isArray(data.products)?data.products:[]).map(p=>({...p,_ai_budget:Number(data.budget||0)}));render()}catch(e){products=DEMO_PRODUCTS.slice();searchMode="classic";const input=document.getElementById("search");if(input)input.value=text;render();showToast(e.message)}}
function add(id){const p=products.find(x=>String(x.id)===String(id));if(!p)return;const stock=Number(p.stock||0);if(stock<=0)return alert(tr("Ce produit est en rupture de stock.","This product is out of stock."));const c=cart(),row=c.find(x=>String(x.product_id)===String(id));if(row){if(row.quantity>=stock)return alert(tr(`Stock maximum atteint : ${stock} unité(s).`,`Maximum stock reached: ${stock} unit(s).`));row.quantity++}else c.push({product_id:p.id,name:p.name,price_fcfa:Number(p.price_fcfa||0),image_url:p.image_url||"",quantity:1});saveCart(c);showToast(tr(`${p.name} a été ajouté au panier.`,`${p.name} was added to your cart.`))}
function showToast(text){let t=document.getElementById("toast");if(!t){t=document.createElement("div");t.id="toast";t.className="toast";document.body.appendChild(t)}t.textContent=text;t.classList.add("show");clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove("show"),2600)}
function verificationMarkup(p){const level=String(p.verified_level||"STANDARD").toUpperCase(),verified=["VERIFIED","PREMIUM"].includes(level),rating=Number(p.rating_average||0),count=Number(p.rating_count||0),score=Number(p.verification_score||0);return `<div class="product-trust"><span class="trust-pill ${verified?'verified':'pending'}">${verified?tr("✓ Egonar vérifié","✓ Egonar verified"):tr("Vérification standard","Standard verification")}</span>${rating?`<span class="rating-pill">★ ${rating.toFixed(1)} <small>(${count})</small></span>`:""}${score?`<span class="score-pill">${score}/100</span>`:""}</div>`}
function render(){const box=document.getElementById("products-list")||document.getElementById("products");if(!box)return;const q=searchMode==="classic"?(document.getElementById("search")?.value||"").trim().toLowerCase():"";let list=products.filter(p=>!category||String(p.category||"").toLowerCase()===category.toLowerCase());if(q)list=list.filter(p=>`${p.name||""} ${p.description||""} ${p.category||""} ${p.sku||""}`.toLowerCase().includes(q));const sort=document.getElementById("sort")?.value;if(sort==="priceAsc")list.sort((a,b)=>Number(a.price_fcfa)-Number(b.price_fcfa));if(sort==="priceDesc")list.sort((a,b)=>Number(b.price_fcfa)-Number(a.price_fcfa));box.innerHTML=list.map(p=>{const stock=Number(p.stock||0),dmax=Number(p.delivery_max_minutes||0),dmin=Number(p.delivery_min_minutes||0),delivery=dmax?`<small class="delivery-pill">🚚 ${dmin?`${dmin}–`:''}${dmax} min · ${esc(p.delivery_city||'Dakar')}</small>`:"";return `<article class="product-card"><a class="product-image" href="produit.html?id=${encodeURIComponent(p.id)}">${p.image_url?`<img src="${esc(p.image_url)}" alt="${esc(p.name)}" loading="lazy" onerror="this.style.display='none'">`:`<div class="image-placeholder">EgonarMarket</div>`}</a><div class="product-body">${verificationMarkup(p)}<span class="badge">${esc(p.category)}</span><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p>${buildAiReasons(p)}${delivery}<div class="product-bottom"><strong>${money(p.price_fcfa)}</strong><button class="add-btn" data-id="${esc(p.id)}" ${stock<=0?'disabled':''}>${stock>0?tr("Ajouter","Add to cart"):tr("Rupture","Out of stock")}</button></div></div></article>`}).join("")||`<div class="empty-state"><h3>${tr("Aucun produit trouvé","No products found")}</h3><p>${tr("Essayez une autre recherche ou catégorie.","Try another search or category.")}</p><button type="button" class="btn" id="reset-search">${tr("Voir tous les produits","View all products")}</button></div>`;const count=document.getElementById("result-count");if(count)count.textContent=tr(`${list.length} produit${list.length>1?'s':''}`,`${list.length} product${list.length===1?'':'s'}`);box.querySelectorAll(".add-btn").forEach(b=>b.onclick=()=>add(b.dataset.id));document.getElementById("reset-search")?.addEventListener("click",()=>{searchMode="classic";category="";aiQueryText="";const i=document.getElementById("search");if(i)i.value="";load()})}
function voiceSearch(){const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition)return alert(tr("La recherche vocale n'est pas disponible sur ce navigateur.","Voice search is not available in this browser."));const r=new Recognition();r.lang=lang()==="en"?"en-US":"fr-FR";r.interimResults=false;r.onresult=e=>{const text=e.results[0][0].transcript,input=document.getElementById("search");if(input)input.value=text;smartSearch(text)};r.start()}
document.addEventListener("DOMContentLoaded",()=>{siteEnhancements();injectAiReasonStyles();document.getElementById("search-form")?.addEventListener("submit",e=>{e.preventDefault();runClassicSearch(document.getElementById("search")?.value||"")});document.getElementById("smart-form")?.addEventListener("submit",e=>{e.preventDefault();smartSearch(document.getElementById("smart-search")?.value||"");document.getElementById("produits")?.scrollIntoView({behavior:"smooth"})});document.getElementById("sort")?.addEventListener("change",render);document.querySelectorAll("[data-category]").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll("[data-category]").forEach(x=>x.classList.remove("active"));b.classList.add("active");category=b.dataset.category||"";searchMode="classic";aiQueryText="";load()}));document.getElementById("voice-search")?.addEventListener("click",voiceSearch);updateCount();load()});
function runClassicSearch(text){searchMode="classic";aiQueryText="";const input=document.getElementById("search");if(input)input.value=String(text||"");render();document.getElementById("produits")?.scrollIntoView({behavior:"smooth"})}
