const foodOffers = [
  { title: "Thiéboudienne traditionnelle", type: "Plat", city: "Dakar", tags: "thieb thieboudienne ceebu jen riz poisson plat senegalais", price: 3500, note: "Plat national · livraison Dakar", image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=85" },
  { title: "Yassa poulet", type: "Plat", city: "Dakar", tags: "yassa poulet oignon citron riz restaurant repas", price: 3000, note: "Préparé à la commande", image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=85" },
  { title: "Poisson grillé & accompagnement", type: "Poissonnerie", city: "Dakar", tags: "poisson frais fruits de mer poissonnerie grillade poisson", price: 4500, note: "Poisson frais · sélection du jour", image: "https://images.unsplash.com/photo-1544943910-4c1dc44aab44?auto=format&fit=crop&w=900&q=85" },
  { title: "Mafé bœuf", type: "Plat", city: "Dakar", tags: "mafe boeuf arachide riz sauce repas senegalais", price: 2500, note: "Sauce arachide · portion généreuse", image: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=85" },
  { title: "Pack famille sénégalais", type: "Menu", city: "Dakar", tags: "famille menu repas thieb yassa mafe partage", price: 12000, note: "Idéal pour 4 personnes", image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=900&q=85" }
];
window.foodOffers = foodOffers;
function foodMoney(value) { return new Intl.NumberFormat("fr-FR").format(value) + " FCFA"; }
function foodText(fr, en) { return window.EgonarI18n?.getLang?.() === "en" ? en : fr; }
function foodApiBase() { return String(window.EgonarPlatformConfig?.apiBase || "").replace(/\/$/, ""); }
function foodApiUrl(path) { return `${foodApiBase()}${path}`; }
async function fetchFoodOffers() { try { const response = await fetch(foodApiUrl("/api/products?universe=SAVEURS"), { headers: { Accept: "application/json" } }); if (!response.ok) throw new Error("catalogue"); const products = await response.json(); return Array.isArray(products) ? products.map(p => ({ title:p.name,type:p.category || foodText("Offre","Offer"),city:p.delivery_city || "Dakar",tags:`${p.name} ${p.category || ""} ${p.subcategory || ""} ${p.description || ""}`,price:Number(p.price_fcfa)||0,oldPrice:p.old_price_fcfa,note:p.delivery_max_minutes ? foodText(`Livraison jusqu'à ${p.delivery_max_minutes} min`,`Delivery up to ${p.delivery_max_minutes} min`) : foodText("Disponible sur EgonarMarket","Available on EgonarMarket"),image:p.image_url || "",id:p.id,stock:Number(p.stock)||0})) : []; } catch { return []; } }
function foodSearchLocal(offers,message) { const text=String(message||"").trim().toLowerCase(); if(!text)return {results:offers,budget:null}; const budgetMatch=text.match(/(?:moins de|à moins de|budget|maximum|max|under|less than)\s*([0-9\s]+)/i)||text.match(/([0-9]{3,})\s*(?:fcfa|f|francs?)/i); const budget=budgetMatch?Number(budgetMatch[1].replace(/\s/g,"")):null; const words=text.normalize("NFD").replace(/[\u0300-\u036f]/g,"").split(/\s+/).filter(w=>w.length>2); const results=offers.filter(item=>{const hay=`${item.title} ${item.type} ${item.city} ${item.tags}`.toLowerCase();return(words.length===0||words.some(w=>hay.includes(w)))&&(!budget||item.price<=budget)}); return {results,budget}; }
function foodAddToCart(button) { const id=button.dataset.id; if(!id){alert(foodText("Cette offre n'est pas encore disponible à l'achat.","This offer is not yet available for purchase."));return;} const cart=JSON.parse(localStorage.getItem("egonarCart")||"[]"); const existing=cart.find(x=>String(x.product_id)===String(id)); if(existing){existing.quantity=Number(existing.quantity||1)+1;}else{cart.push({product_id:id,quantity:1});} localStorage.setItem("egonarCart",JSON.stringify(cart)); window.location.href="panier.html"; }
window.foodAddToCart=foodAddToCart;
function renderFoodResults(results,query,budget) { const box=document.getElementById("food-smart-results");if(!box)return;const budgetText=budget?` · ${foodText("budget","budget")} ${foodMoney(budget)}`:"";const suggestions=foodText("suggestion","suggestion");box.innerHTML=`<div class="food-result-head"><strong>${foodText("Résultats pour","Results for")} « ${query} »${budgetText}</strong><span>${results.length} ${suggestions}${results.length>1?"s":""}</span></div><div class="menu-grid">${results.map(item=>`<article class="menu-card"><img src="${item.image}" alt="${item.title}" loading="lazy" style="width:100%;height:210px;object-fit:cover;display:block;border-radius:16px 16px 0 0"><div class="menu-body"><span class="badge">${item.type}</span><h3>${item.title}</h3><p>${item.city} · ${item.note}</p><div class="product-bottom"><strong>${foodMoney(item.price)}</strong>${item.id?`<button type="button" class="btn primary food-add-cart" data-id="${item.id}">${foodText("Ajouter au panier","Add to cart")}</button>`:`<a class="btn primary" href="#explorer">${foodText("Voir l'offre","View offer")}</a>`}</div></div></article>`).join("")}</div>`;box.querySelectorAll(".food-add-cart").forEach(button=>button.addEventListener("click",()=>foodAddToCart(button)));box.scrollIntoView({behavior:"smooth",block:"start"}); }
async function foodSearch(message) { const text=String(message||"").trim();if(!text)return;const live=await fetchFoodOffers();const offers=live.length?live:foodOffers;const local=foodSearchLocal(offers,text);const results=local.results.length?local.results:offers.slice(0,3);renderFoodResults(results,text.toLowerCase(),local.budget); }
document.addEventListener("DOMContentLoaded",()=>{const form=document.querySelector(".food-search form");const input=form?.querySelector("input");form?.addEventListener("submit",e=>{e.preventDefault();foodSearch(input?.value||"")});form?.querySelector("button")?.addEventListener("click",()=>foodSearch(input?.value||""));if(!document.getElementById("egonar-voice-assistant")){const script=document.createElement("script");script.src="assistant-voice.js";document.body.appendChild(script)}});