const SUPPLIER_API=window.EGONAR_SUPPLIER_API || "/supplier-api";const $=id=>document.getElementById(id);const L=()=>localStorage.getItem("egonar_language")==="en";const T=(fr,en)=>L()?en:fr;const money=n=>new Intl.NumberFormat("fr-FR").format(Number(n)||0)+" FCFA";const call=(path,options={})=>fetch(SUPPLIER_API+path,{credentials:"include",...options}).then(async r=>({ok:r.ok,data:await r.json().catch(()=>({}))}));const esc=s=>String(s??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));const U={MARKET:"MARKET",SAVEURS:"SAVEURS",EVASION:"ÉVASION"};const PS={APPROVED:["Publié","Published"],PENDING:["En validation","Pending approval"],REJECTED:["Refusé","Rejected"]};const OS={EN_ATTENTE_PAIEMENT:"En attente de paiement",CONFIRMEE:"Confirmée",PREPARATION:"En préparation",EXPEDIEE:"Expédiée",EN_LIVRAISON:"En livraison",LIVREE:"Livrée",ANNULEE:"Annulée"};
const TIMER_STATE_LABELS={ON_TIME:"Dans les temps",WARNING:"Attention",CRITICAL:"Urgent",OVERDUE:"En retard"};
function formatTimerSeconds(total){let s=Math.max(0,Math.floor(Number(total)||0));const h=Math.floor(s/3600);s%=3600;const m=Math.floor(s/60);s%=60;return [h,m,s].map(v=>String(v).padStart(2,"0")).join(":");}
function timerHtml(t){if(!t)return "";return '<div class="workflow-timer '+String(t.state||"ON_TIME").toLowerCase().replace("_","-")+'" data-due-at="'+esc(t.due_at||"")+'" data-started-at="'+esc(t.started_at||"")+'" data-duration-seconds="'+(Number(t.duration_seconds)||0)+'"><div class="workflow-timer-head"><span class="workflow-timer-label">Minuterie — '+esc(t.stage_label||"Étape")+'</span><strong class="workflow-timer-countdown">00:00:00</strong></div><div class="workflow-timer-meta"><span class="workflow-timer-state">'+(TIMER_STATE_LABELS[t.state]||"En cours")+'</span><span class="workflow-timer-percent">0%</span></div><div class="workflow-timer-bar"><span class="workflow-timer-progress"></span></div></div>';}
function tickTimers(){document.querySelectorAll(".workflow-timer[data-due-at]").forEach(el=>{const due=Date.parse(el.dataset.dueAt||"");const started=Date.parse(el.dataset.startedAt||"");const duration=Number(el.dataset.durationSeconds)||1;if(!Number.isFinite(due))return;const now=Date.now();const remaining=Math.floor((due-now)/1000);const elapsed=started?Math.max(0,Math.floor((now-started)/1000)):Math.max(0,duration-Math.max(0,remaining));const progress=Math.min(100,Math.max(0,elapsed/duration*100));let state="ON_TIME";if(remaining<=0)state="OVERDUE";else if(progress>=90)state="CRITICAL";else if(progress>=70)state="WARNING";el.classList.remove("on-time","warning","critical","overdue");el.classList.add(state.toLowerCase().replace("_","-"));const countdown=el.querySelector(".workflow-timer-countdown");if(countdown)countdown.textContent=remaining<=0?"+"+formatTimerSeconds(Math.abs(remaining))+" de retard":formatTimerSeconds(remaining);const stateEl=el.querySelector(".workflow-timer-state");if(stateEl)stateEl.textContent=TIMER_STATE_LABELS[state];const pct=el.querySelector(".workflow-timer-percent");if(pct)pct.textContent=Math.round(progress)+"%";const bar=el.querySelector(".workflow-timer-progress");if(bar)bar.style.width=Math.min(100,progress)+"%";});}let products=[],orders=[];
function message(id,text,ok=false){const el=$(id);if(!el)return;el.textContent=text||"";el.className=text?`state ${ok?"success":"error"}`:"";}
function setSupplierProfile(profile){const form=$("supplier-profile-form");if(!form||!profile)return;for(const key of ["business_name","contact_name","phone","address","city","website","logo_url"])if(form.elements[key])form.elements[key].value=profile[key]||"";setSupplierLogoPreview(profile.logo_url||"");}
function setSupplierLogoPreview(url){const box=$("supplier-logo-preview");if(!box)return;if(!url){box.hidden=true;box.innerHTML="";return;}box.hidden=false;box.innerHTML='<div class="supplier-preview-item"><img src="'+esc(url)+'" alt="'+T("Logo actuel","Current logo")+'"><small>'+T("Logo actuel","Current logo")+'</small></div>';}
async function loadSupplierProfile(){const r=await call("/api/supplier/me");if(r.ok)setSupplierProfile(r.data);}
$("supplier-logo")?.addEventListener("change",e=>{const file=e.currentTarget.files?.[0];const box=$("supplier-logo-preview");if(!file){setSupplierLogoPreview("");return;}if(!["image/jpeg","image/png","image/webp","image/gif"].includes(file.type))return message("supplier-profile-msg",T("Format d’image non pris en charge.","Unsupported image format."));if(file.size>7*1024*1024)return message("supplier-profile-msg",T("Le logo dépasse 7 Mo.","Logo exceeds 7 MB."));const url=URL.createObjectURL(file);box.hidden=false;box.innerHTML='<div class="supplier-preview-item"><img src="'+esc(url)+'" alt="'+T("Aperçu du logo","Logo preview")+'"><small>'+esc(file.name)+'</small></div>';});
$("supplier-profile-form")?.addEventListener("submit",async e=>{e.preventDefault();const form=e.currentTarget;const b=Object.fromEntries(new FormData(form));delete b.logo;if(form.elements.logo?.files?.[0]){try{message("supplier-profile-msg",T("Téléversement du logo…","Uploading logo…"),true);const uploaded=await uploadSupplierImages([form.elements.logo.files[0]],"");b.logo_url=uploaded[0]||b.logo_url||"";}catch(error){return message("supplier-profile-msg",error.message||T("Téléversement impossible.","Upload failed."),false);}}try{const r=await call("/api/supplier/profile",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(b)});message("supplier-profile-msg",r.data.error||T("Profil enregistré.","Profile saved."),r.ok);if(r.ok)setSupplierProfile(r.data);}catch(error){message("supplier-profile-msg",T("Impossible d’enregistrer le profil.","Unable to save profile."),false);}});
async function boot(){const me=await call("/api/supplier/me");if(me.ok){$("auth").hidden=true;$("panel").hidden=false;$("logout").hidden=false;setSupplierProfile(me.data);await refresh();}}
$("register")?.addEventListener("submit",async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget));const r=await call("/api/supplier/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});message("register-msg",r.data.error||r.data.message||T("Demande envoyée.","Request sent."),r.ok);if(r.ok)e.currentTarget.reset();});
$("login")?.addEventListener("submit",async e=>{e.preventDefault();const r=await call("/api/supplier/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});if(!r.ok)return message("login-msg",r.data.error||T("Connexion impossible.","Unable to sign in."));location.reload();});
$("logout")?.addEventListener("click",async()=>{await call("/api/supplier/logout",{method:"POST"});location.reload();});
async function uploadSupplierImages(files,universe){
  const selected=Array.from(files||[]).slice(0,8);const allowed=["image/jpeg","image/png","image/webp","image/gif"];
  for(const file of selected){if(!allowed.includes(file.type))throw new Error(T("Format d’image non pris en charge.","Unsupported image format."));if(file.size>7*1024*1024)throw new Error(T("Chaque image doit faire au maximum 7 Mo.","Each image must be at most 7 MB."));}
  const urls=[];
  for(const file of selected){const fd=new FormData();fd.append("image",file);if(universe)fd.append("universe",universe);const r=await call("/api/supplier/upload-image",{method:"POST",body:fd});if(!r.ok)throw new Error(r.data?.error||T("Téléversement impossible.","Upload failed."));if(r.data?.url)urls.push(r.data.url);}
  return urls;
}
function previewSupplierImages(files,current=[]){
  const box=$("supplier-product-image-preview");const urls=[...current];for(const file of Array.from(files||[]).slice(0,8-urls.length))urls.push(URL.createObjectURL(file));
  if(!urls.length){box.hidden=true;box.innerHTML="";return;}
  box.hidden=false;box.innerHTML=urls.map((url,i)=>'<div class="supplier-preview-item"><img src="'+esc(url)+'" alt="'+T("Image ","Image ")+(i+1)+'"><small>'+(url.startsWith("blob:")?T("Nouvelle image","New image"):T("Image actuelle","Current image"))+'</small></div>').join("");
}
function setSupplierImagePreview(urls){
  const list=Array.isArray(urls)?urls:(urls?[urls]:[]);const box=$("supplier-product-image-preview");
  if(!list.length){box.hidden=true;box.innerHTML="";return;}
  box.hidden=false;box.innerHTML=list.map((url,i)=>'<div class="supplier-preview-item"><img src="'+esc(url)+'" alt="'+T("Image ","Image ")+(i+1)+'"><small>'+T("Image ","Image ")+(i+1)+'</small></div>').join("");
}
$("supplier-product-image")?.addEventListener("change",e=>{let current=[];try{current=JSON.parse($("product-form").elements.image_gallery.value||"[]");}catch{}previewSupplierImages(e.currentTarget.files,current);});
$("product-form")?.addEventListener("submit",async e=>{e.preventDefault();const form=e.currentTarget,b=Object.fromEntries(new FormData(form)),id=b.id;delete b.id;delete b.image;let gallery=[];try{gallery=JSON.parse(b.image_gallery||"[]");}catch{}delete b.image_gallery;["price_fcfa","old_price_fcfa","stock"].forEach(k=>b[k]===""?b[k]=null:b[k]=Number(b[k]));try{if(form.elements.image?.files?.length){message("product-msg",T("Téléversement des images…","Uploading images…"),true);const uploaded=await uploadSupplierImages(form.elements.image.files,form.elements.universe.value);gallery=[...new Set([...gallery,...uploaded])].slice(0,8);b.image_gallery=gallery;b.image_url=gallery[0]||b.image_url||"";}else if(gallery.length){b.image_gallery=gallery;b.image_url=gallery[0]||b.image_url||"";}const r=await call(id?"/api/supplier/products/"+encodeURIComponent(id):"/api/supplier/products",{method:id?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(b)});message("product-msg",r.data.error||T(id?"Produit renvoyé en validation.":"Produit soumis pour validation.",id?"Product resubmitted for approval.":"Product submitted for approval."),r.ok);if(r.ok){resetProductForm();await refresh();}}catch(error){message("product-msg",error.message||T("Téléversement impossible.","Upload failed."),false);}});
$("cancel-edit")?.addEventListener("click",resetProductForm);
async function deactivateProduct(id){if(!confirm(T("Désactiver ce produit ?","Deactivate this product?")))return;const r=await call(`/api/supplier/products/${encodeURIComponent(id)}`,{method:"DELETE"});if(!r.ok)return message("product-msg",r.data.error||T("Opération impossible.","Operation failed."));await refresh();}
function drawProducts(){const q=$("universe-filter")?.value||"";const list=products.filter(p=>!q||p.universe===q);$("product-summary").textContent=`${list.length} ${T(list.length>1?"produits":"produit",list.length>1?"products":"product")}`;$("products").innerHTML=list.map(p=>{const st=PS[p.approval_status]||[p.approval_status,p.approval_status];return `<article class="admin-order-card"><div class="admin-order-top"><div><p class="eyebrow">${esc(U[p.universe]||p.universe||"UNIVERS")}</p><h3>${esc(p.name)}</h3><p class="muted">${esc(p.category||"")} ${p.subcategory?"· "+esc(p.subcategory):""} · ${money(p.price_fcfa)} · stock ${Number(p.stock)||0}</p></div><span class="admin-order-badge">${esc(L()?st[1]:st[0])}</span></div><div class="admin-order-grid"><div><p class="small muted">${esc(p.sku||"SKU non renseigné")}</p><p class="small">${p.active?T("Actuellement actif","Currently active"):T("Non publié","Not published")}</p></div><div class="admin-order-actions"><button class="btn secondary" type="button" onclick="editProduct('${esc(p.id)}')">${T("Modifier","Edit")}</button><button class="btn secondary" type="button" onclick="deactivateProduct('${esc(p.id)}')">${T("Désactiver","Deactivate")}</button></div></div></article>`}).join("")||`<p class="muted">${T("Aucun produit dans cet univers.","No products in this universe.")}</p>`;}
async function confirmOrderStep(id,action){const r=await call(`/api/supplier/orders/${encodeURIComponent(id)}/workflow`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action})});if(!r.ok)return message("product-msg",r.data.error||T("Étape impossible.","Unable to confirm step."));await refresh();}
function workflowAction(o){if(o.status==="CONFIRMEE")return `<button class="btn primary" type="button" onclick="confirmOrderStep('${esc(o.id)}','PREPARE')">${T("Démarrer la préparation","Start preparation")}</button>`;if(o.status==="PREPARATION")return `<button class="btn primary" type="button" onclick="confirmOrderStep('${esc(o.id)}','SHIP')">${T("Confirmer l’expédition","Confirm shipment")}</button>`;return "";}
function drawOrders(){$("orders").innerHTML=orders.map(o=>{const items=Array.isArray(o.items)?o.items:[];return `<article class="admin-order-card ${o.status==="ANNULEE"?"is-cancelled":""}"><div class="admin-order-top"><div><p class="eyebrow">COMMANDE</p><h3>${esc(o.order_number)}</h3><p class="muted">${esc(o.customer_name||"Client")} · ${esc(o.customer_phone||"")} · ${money(o.supplier_total_fcfa)}</p></div><div class="admin-order-actions"><span class="admin-order-badge">${esc(OS[o.status]||o.status||"Inconnu")}</span>${workflowAction(o)}</div></div>${timerHtml(o.timer)}<div class="admin-order-grid"><div><h4>Livraison</h4><p>${esc(o.customer_address||"Adresse non renseignée")}</p><p>${esc(o.customer_city||"")}</p><p class="small muted">Paiement : ${esc(o.payment_method||"Non renseigné")} ${o.payment_status?"· "+esc(o.payment_status):""}</p></div><div><h4>Vos articles</h4><ul class="admin-order-items">${items.map(i=>`<li><span>${esc(i.name)} × ${Number(i.quantity)||1}</span><strong>${money((Number(i.unit_price_fcfa)||0)*(Number(i.quantity)||1))}</strong></li>`).join("")}</ul></div></div></article>`}).join("")||`<p class="muted">${T("Aucune commande pour le moment.","No orders yet.")}</p>`;}

async function refresh(){const [me,stats,sales,pr,or]=await Promise.all([call("/api/supplier/me"),call("/api/supplier/stats"),call("/api/supplier/sales-stats"),call("/api/supplier/products"),call("/api/supplier/orders")]);if(!me.ok||!stats.ok||!sales.ok||!pr.ok||!or.ok)return;products=pr.data||[];orders=or.data||[];$("active-count").textContent=stats.data.active_products??0;$("pending-count").textContent=stats.data.pending_products??0;$("stock-count").textContent=stats.data.total_stock??0;$("sales-count").textContent=money(sales.data.gross_sales_fcfa);$("orders-count").textContent=sales.data.orders_count??0;$("units-count").textContent=sales.data.units_sold??0;$("commission-count").textContent=money(sales.data.estimated_commission_fcfa);drawProducts();drawOrders();}
boot();
setInterval(()=>{if(!$("panel").hidden)refresh();},30000);
setInterval(tickTimers,1000);function resetProductForm(){const f=$("product-form");if(!f)return;f.reset();f.elements.id.value="";f.elements.image_url.value="";f.elements.image_gallery.value="";f.elements.universe.value="MARKET";setSupplierImagePreview([]);$("form-title").textContent=T("Soumettre un produit","Submit a product");$("submit-product").textContent=T("Soumettre pour validation","Submit for approval");$("cancel-edit").hidden=true;}
function editProduct(id){const p=products.find(x=>x.id===id);if(!p)return;const f=$("product-form");Object.entries({id:p.id,universe:p.universe||"MARKET",name:p.name||"",category:p.category||"",subcategory:p.subcategory||"",price_fcfa:p.price_fcfa??"",old_price_fcfa:p.old_price_fcfa??"",stock:p.stock??0,sku:p.sku||"",image_url:p.image_url||"",description:p.description||""}).forEach(([k,v])=>f.elements[k].value=v);const gallery=Array.isArray(p.image_gallery)&&p.image_gallery.length?p.image_gallery:(p.image_url?[p.image_url]:[]);f.elements.image_gallery.value=JSON.stringify(gallery);$("supplier-product-image").value="";setSupplierImagePreview(gallery);$("form-title").textContent=T("Modifier et resoumettre","Edit and resubmit");$("submit-product").textContent=T("Renvoyer en validation","Resubmit for approval");$("cancel-edit").hidden=false;f.scrollIntoView({behavior:"smooth",block:"start"});}
async function deactivateProduct(id){if(!confirm(T("Désactiver ce produit ?","Deactivate this product?")))return;const r=await call(`/api/supplier/products/${encodeURIComponent(id)}`,{method:"DELETE"});if(!r.ok)return message("product-msg",r.data.error||T("Opération impossible.","Operation failed."));await refresh();}
function drawProducts(){const q=$("universe-filter")?.value||"";const list=products.filter(p=>!q||p.universe===q);$("product-summary").textContent=`${list.length} ${T(list.length>1?"produits":"produit",list.length>1?"products":"product")}`;$("products").innerHTML=list.map(p=>{const st=PS[p.approval_status]||[p.approval_status,p.approval_status];return `<article class="admin-order-card"><div class="admin-order-top"><div><p class="eyebrow">${esc(U[p.universe]||p.universe||"UNIVERS")}</p><h3>${esc(p.name)}</h3><p class="muted">${esc(p.category||"")} ${p.subcategory?"· "+esc(p.subcategory):""} · ${money(p.price_fcfa)} · stock ${Number(p.stock)||0}</p></div><span class="admin-order-badge">${esc(L()?st[1]:st[0])}</span></div><div class="admin-order-grid"><div><p class="small muted">${esc(p.sku||"SKU non renseigné")}</p><p class="small">${p.active?T("Actuellement actif","Currently active"):T("Non publié","Not published")}</p></div><div class="admin-order-actions"><button class="btn secondary" type="button" onclick="editProduct('${esc(p.id)}')">${T("Modifier","Edit")}</button><button class="btn secondary" type="button" onclick="deactivateProduct('${esc(p.id)}')">${T("Désactiver","Deactivate")}</button></div></div></article>`}).join("")||`<p class="muted">${T("Aucun produit dans cet univers.","No products in this universe.")}</p>`;}
async function confirmOrderStep(id,action){const r=await call(`/api/supplier/orders/${encodeURIComponent(id)}/workflow`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action})});if(!r.ok)return message("product-msg",r.data.error||T("Étape impossible.","Unable to confirm step."));await refresh();}
function workflowAction(o){if(o.status==="CONFIRMEE")return `<button class="btn primary" type="button" onclick="confirmOrderStep('${esc(o.id)}','PREPARE')">${T("Démarrer la préparation","Start preparation")}</button>`;if(o.status==="PREPARATION")return `<button class="btn primary" type="button" onclick="confirmOrderStep('${esc(o.id)}','SHIP')">${T("Confirmer l’expédition","Confirm shipment")}</button>`;return "";}
function drawOrders(){$("orders").innerHTML=orders.map(o=>{const items=Array.isArray(o.items)?o.items:[];return `<article class="admin-order-card ${o.status==="ANNULEE"?"is-cancelled":""}"><div class="admin-order-top"><div><p class="eyebrow">COMMANDE</p><h3>${esc(o.order_number)}</h3><p class="muted">${esc(o.customer_name||"Client")} · ${esc(o.customer_phone||"")} · ${money(o.supplier_total_fcfa)}</p></div><div class="admin-order-actions"><span class="admin-order-badge">${esc(OS[o.status]||o.status||"Inconnu")}</span>${workflowAction(o)}</div></div>${timerHtml(o.timer)}<div class="admin-order-grid"><div><h4>Livraison</h4><p>${esc(o.customer_address||"Adresse non renseignée")}</p><p>${esc(o.customer_city||"")}</p><p class="small muted">Paiement : ${esc(o.payment_method||"Non renseigné")} ${o.payment_status?"· "+esc(o.payment_status):""}</p></div><div><h4>Vos articles</h4><ul class="admin-order-items">${items.map(i=>`<li><span>${esc(i.name)} × ${Number(i.quantity)||1}</span><strong>${money((Number(i.unit_price_fcfa)||0)*(Number(i.quantity)||1))}</strong></li>`).join("")}</ul></div></div></article>`}).join("")||`<p class="muted">${T("Aucune commande pour le moment.","No orders yet.")}</p>`;}

async function refresh(){const [me,stats,sales,pr,or]=await Promise.all([call("/api/supplier/me"),call("/api/supplier/stats"),call("/api/supplier/sales-stats"),call("/api/supplier/products"),call("/api/supplier/orders")]);if(!me.ok||!stats.ok||!sales.ok||!pr.ok||!or.ok)return;products=pr.data||[];orders=or.data||[];$("active-count").textContent=stats.data.active_products??0;$("pending-count").textContent=stats.data.pending_products??0;$("stock-count").textContent=stats.data.total_stock??0;$("sales-count").textContent=money(sales.data.gross_sales_fcfa);$("orders-count").textContent=sales.data.orders_count??0;$("units-count").textContent=sales.data.units_sold??0;$("commission-count").textContent=money(sales.data.estimated_commission_fcfa);drawProducts();drawOrders();}
boot();
setInterval(()=>{if(!$("panel").hidden)refresh();},30000);
setInterval(tickTimers,1000);function resetProductForm(){const f=$("product-form");if(!f)return;f.reset();f.elements.id.value="";f.elements.image_url.value="";f.elements.image_gallery.value="";f.elements.universe.value="MARKET";setSupplierImagePreview([]);$("form-title").textContent=T("Soumettre un produit","Submit a product");$("submit-product").textContent=T("Soumettre pour validation","Submit for approval");$("cancel-edit").hidden=true;}

