import React, { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { APP_NAME, MOBILE_ROLE } from "./config";
import { adminApi, supplierApi } from "./api";

const colors = { bg: "#f6f8fb", card: "#fff", ink: "#111827", muted: "#6b7280", accent: "#2563eb", danger: "#b42318", border: "#e5e7eb", ok: "#067647", warn: "#9a6700" };
const arr = (value, keys = []) => { if (Array.isArray(value)) return value; for (const key of keys) if (Array.isArray(value?.[key])) return value[key]; return []; };

function Button({ title, onPress, secondary = false, danger = false, disabled = false }) { return <Pressable disabled={disabled} onPress={onPress} style={({ pressed }) => [styles.button, secondary && styles.secondary, danger && styles.danger, disabled && styles.disabled, pressed && styles.pressed]}><Text style={[styles.buttonText, secondary && styles.secondaryText, danger && styles.dangerText]}>{title}</Text></Pressable>; }
function Header({ title, subtitle, onLogout }) { return <View style={styles.header}><View><Text style={styles.headerTitle}>{title}</Text><Text style={styles.headerSub}>{subtitle}</Text></View><Pressable onPress={onLogout}><Text style={styles.logout}>Déconnexion</Text></Pressable></View>; }
function Stat({ label, value }) { return <View style={styles.stat}><Text style={styles.statValue}>{String(value)}</Text><Text style={styles.statLabel}>{label}</Text></View>; }

function Login({ onLogin }) {
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  async function submit(){setBusy(true);setError("");try{if(MOBILE_ROLE==="admin")await adminApi.login(email.trim(),password);else await supplierApi.login(email.trim(),password);await onLogin();}catch(e){setError(e.message||"Connexion impossible.");}finally{setBusy(false);}}
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.login}><Text style={styles.kicker}>EGONARMARKET</Text><Text style={styles.loginTitle}>{APP_NAME}</Text><Text style={styles.subtitle}>{MOBILE_ROLE==="admin"?"Pilotage sécurisé de la plateforme":"Votre espace professionnel fournisseur"}</Text><View style={styles.card}><Text style={styles.cardTitle}>Connexion</Text><TextInput autoCapitalize="none" keyboardType="email-address" placeholder="Email" placeholderTextColor="#9ca3af" value={email} onChangeText={setEmail} style={styles.input}/><TextInput secureTextEntry placeholder="Mot de passe" placeholderTextColor="#9ca3af" value={password} onChangeText={setPassword} style={styles.input}/>{error?<Text style={styles.error}>{error}</Text>:null}<Button title={busy?"Connexion…":"Se connecter"} onPress={submit} disabled={busy||!email||!password}/></View></ScrollView></SafeAreaView>;
}

function AdminHome({ onLogout }) {
  const [suppliers,setSuppliers]=useState([]); const [products,setProducts]=useState([]); const [busy,setBusy]=useState(true); const [message,setMessage]=useState("");
  const load=async()=>{setBusy(true);try{const [s,p]=await Promise.all([adminApi.suppliers(),adminApi.pendingProducts()]);setSuppliers(arr(s,["suppliers","data","items"]));setProducts(arr(p,["products","data","items"]));setMessage("");}catch(e){setMessage(e.message||"Impossible de charger le tableau de bord.");}finally{setBusy(false);}};
  useEffect(()=>{load();},[]);
  const pending=suppliers.filter(x=>String(x?.status||"").toUpperCase()==="PENDING").length;
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.page}><Header title="Egonar Admin" subtitle="Vue globale" onLogout={onLogout}/><View style={styles.stats}><Stat label="Fournisseurs" value={suppliers.length}/><Stat label="À valider" value={pending}/><Stat label="Produits en attente" value={products.length}/></View>{message?<Text style={styles.error}>{message}</Text>:null}<Text style={styles.section}>Produits à valider</Text>{busy?<ActivityIndicator/>:products.length?products.slice(0,10).map(p=><View style={styles.row} key={p.id}><View style={styles.main}><Text style={styles.rowTitle}>{p.name||"Produit"}</Text><Text style={styles.meta}>{p.business_name||"Fournisseur"} · {p.price_fcfa??"—"} FCFA · stock {p.stock??"—"}</Text></View><View style={styles.actions}><Button title="Approuver" onPress={async()=>{await adminApi.approveProduct(p.id,"APPROVED");load();}}/><Button title="Refuser" secondary onPress={async()=>{await adminApi.approveProduct(p.id,"REJECTED");load();}}/></View></View>):<Text style={styles.muted}>Aucun produit en attente.</Text>}<Text style={styles.section}>Fournisseurs</Text>{suppliers.length?suppliers.slice(0,20).map(s=><View style={styles.row} key={s.id}><View style={styles.main}><Text style={styles.rowTitle}>{s.business_name||s.name||"Fournisseur"}</Text><Text style={styles.meta}>{s.contact_name||""}{s.email?` · ${s.email}`:""}</Text></View><View style={styles.actions}><Text style={styles.status}>{s.status||"—"}</Text>{String(s.status).toUpperCase()==="PENDING"?<Button title="Valider" onPress={async()=>{await adminApi.updateSupplierStatus(s.id,"APPROVED");load();}}/>:null}{String(s.status).toUpperCase()==="APPROVED"?<Button title="Suspendre" secondary onPress={async()=>{await adminApi.updateSupplierStatus(s.id,"SUSPENDED");load();}}/>:null}</View></View>):<Text style={styles.muted}>Aucun fournisseur à afficher.</Text>}<Button title="Actualiser" secondary onPress={load}/></ScrollView></SafeAreaView>;
}

function SupplierHome({ onLogout }) {
  const [stats,setStats]=useState(null); const [products,setProducts]=useState([]); const [me,setMe]=useState(null); const [error,setError]=useState(""); const [showAdd,setShowAdd]=useState(false); const [editingId,setEditingId]=useState(null); const [saving,setSaving]=useState(false); const [form,setForm]=useState({name:"",category:"",description:"",price_fcfa:"",old_price_fcfa:"",stock:"",sku:"",image_url:""});
  const load=async()=>{try{const [m,s,p]=await Promise.all([supplierApi.me(),supplierApi.stats(),supplierApi.products()]);setMe(m?.supplier||m?.data||m);setStats(s?.stats||s?.data||s);setProducts(arr(p,["products","data","items"]));setError("");}catch(e){setError(e.message||"Impossible de charger votre espace.");}};
  useEffect(()=>{load();},[]);
  const reset=()=>{setForm({name:"",category:"",description:"",price_fcfa:"",old_price_fcfa:"",stock:"",sku:"",image_url:""});setEditingId(null);setShowAdd(false);};
  const edit=p=>{setEditingId(p.id);setShowAdd(true);setForm({name:p.name||"",category:p.category||"",description:p.description||"",price_fcfa:String(p.price_fcfa??""),old_price_fcfa:String(p.old_price_fcfa??""),stock:String(p.stock??""),sku:p.sku||"",image_url:p.image_url||""});};
  const save=async()=>{setSaving(true);setError("");try{const payload={...form,price_fcfa:Number(form.price_fcfa),old_price_fcfa:form.old_price_fcfa===""?null:Number(form.old_price_fcfa),stock:Number(form.stock||0)};if(editingId)await supplierApi.updateProduct(editingId,payload);else await supplierApi.createProduct(payload);reset();await load();}catch(e){setError(e.message||"Impossible d'enregistrer l'offre.");}finally{setSaving(false);}};
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.page}><Header title={me?.business_name||"Espace fournisseur"} subtitle="Mon activité" onLogout={onLogout}/><View style={styles.stats}><Stat label="Offres actives" value={stats?.active_products??"—"}/><Stat label="En validation" value={stats?.pending_products??"—"}/><Stat label="Stock / capacité" value={stats?.total_stock??"—"}/></View>{error?<Text style={styles.error}>{error}</Text>:null}<View style={styles.toolbar}><Text style={styles.section}>Mes offres</Text><Button title={showAdd?"Fermer":"+ Ajouter"} secondary onPress={()=>showAdd?reset():setShowAdd(true)}/></View>{showAdd?<View style={styles.card}><Text style={styles.cardTitle}>{editingId?"Modifier l'offre":"Nouvelle offre"}</Text>{["name","category","description","price_fcfa","old_price_fcfa","stock","sku","image_url"].map(k=><TextInput key={k} placeholder={k==="name"?"Nom":k==="category"?"Catégorie":k==="description"?"Description":k==="price_fcfa"?"Prix en FCFA":k==="old_price_fcfa"?"Ancien prix (optionnel)":k==="stock"?"Stock / capacité":k==="sku"?"Référence (optionnel)":"URL de l'image"} placeholderTextColor="#9ca3af" keyboardType={["price_fcfa","old_price_fcfa","stock"].includes(k)?"numeric":"default"} multiline={k==="description"} value={form[k]} onChangeText={v=>setForm({...form,[k]:v})} style={[styles.input,k==="description"&&styles.textarea]}/>)}<Button title={saving?"Enregistrement…":editingId?"Enregistrer les modifications":"Soumettre à Egonar"} onPress={save} disabled={saving||!form.name||!form.category||!form.price_fcfa}/>{editingId?<Button title="Annuler" secondary onPress={reset}/>:null}</View>:null}{products.slice(0,20).map(p=><View style={styles.row} key={p.id}><View style={styles.main}><Text style={styles.rowTitle}>{p.name||"Offre"}</Text><Text style={styles.meta}>{p.price_fcfa??"—"} FCFA · stock {p.stock??"—"} · {p.approval_status||"—"}</Text></View><View style={styles.actions}><Button title="Modifier" secondary onPress={()=>edit(p)}/>{p.active?<Button title="Désactiver" danger onPress={async()=>{await supplierApi.deactivateProduct(p.id);load();}}/>:null}</View></View>)}<Button title="Actualiser" secondary onPress={load}/></ScrollView></SafeAreaView>;
}

export default function AppSafe(){const [session,setSession]=useState(false);const [checking,setChecking]=useState(true);async function check(){try{if(MOBILE_ROLE==="admin")await adminApi.me();else await supplierApi.me();setSession(true);}catch{setSession(false);}finally{setChecking(false);}}useEffect(()=>{check();},[]);if(checking)return <SafeAreaView style={styles.safe}><View style={styles.center}><ActivityIndicator size="large"/><Text style={styles.muted}>Chargement…</Text></View></SafeAreaView>;if(!session)return <Login onLogin={check}/>;const logout=async()=>{try{if(MOBILE_ROLE==="admin")await adminApi.logout();else await supplierApi.logout();}finally{setSession(false);}};return MOBILE_ROLE==="admin"?<AdminHome onLogout={logout}/>:<SupplierHome onLogout={logout}/>;}

const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.bg},page:{padding:20,paddingBottom:48},login:{flexGrow:1,justifyContent:"center",padding:24},center:{flex:1,alignItems:"center",justifyContent:"center",gap:10},kicker:{color:colors.accent,fontSize:12,fontWeight:"900",letterSpacing:2},loginTitle:{fontSize:36,fontWeight:"900",color:colors.ink,marginTop:8},subtitle:{color:colors.muted,fontSize:15,lineHeight:22,marginTop:8,marginBottom:24},card:{backgroundColor:colors.card,borderRadius:20,padding:20,borderWidth:1,borderColor:colors.border,gap:10},cardTitle:{fontSize:22,fontWeight:"900",color:colors.ink},input:{height:52,borderWidth:1,borderColor:colors.border,borderRadius:14,paddingHorizontal:15,color:colors.ink,backgroundColor:"#fff",marginBottom:8},textarea:{height:100,paddingTop:14,textAlignVertical:"top"},button:{backgroundColor:colors.ink,minHeight:44,paddingHorizontal:14,borderRadius:12,alignItems:"center",justifyContent:"center",marginTop:5},secondary:{backgroundColor:"#fff",borderWidth:1,borderColor:colors.border},danger:{backgroundColor:"#fff1f0",borderWidth:1,borderColor:"#f5c2c0"},disabled:{opacity:.45},pressed:{transform:[{scale:.98}]},buttonText:{color:"#fff",fontWeight:"800"},secondaryText:{color:colors.ink},dangerText:{color:colors.danger},error:{color:colors.danger,backgroundColor:"#fff1f0",borderWidth:1,borderColor:"#f5c2c0",padding:12,borderRadius:12,marginBottom:12},header:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginBottom:20},headerTitle:{fontSize:28,fontWeight:"900",color:colors.ink},headerSub:{color:colors.muted,marginTop:4},logout:{color:colors.accent,fontWeight:"800"},stats:{flexDirection:"row",gap:10,marginBottom:22},stat:{flex:1,backgroundColor:colors.card,borderRadius:16,padding:15,borderWidth:1,borderColor:colors.border},statValue:{fontSize:25,fontWeight:"900",color:colors.ink},statLabel:{color:colors.muted,fontSize:12,marginTop:4},section:{fontSize:21,fontWeight:"900",color:colors.ink,marginTop:8,marginBottom:12},toolbar:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginBottom:8},row:{backgroundColor:colors.card,borderRadius:16,borderWidth:1,borderColor:colors.border,padding:14,marginBottom:10,flexDirection:"row",gap:10},main:{flex:1},rowTitle:{fontWeight:"900",color:colors.ink},meta:{color:colors.muted,fontSize:12,lineHeight:18,marginTop:5},actions:{width:112,gap:3},status:{fontSize:11,fontWeight:"800",color:colors.ok,marginBottom:3},muted:{color:colors.muted}});
