const API=location.hostname.endsWith('.app.github.dev')?location.origin.replace('-8080.','-3000.')+'/api':'/api';
const DEMO=[
{id:'demo-1',name:'T-shirt qualité premium',category:'Mode',description:'T-shirt confortable et élégant.',price_fcfa:10000,stock:20,image_url:'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80'},
{id:'demo-2',name:'Sac Élégance',category:'Accessoires',description:'Sac moderne et pratique.',price_fcfa:18000,stock:12,image_url:'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80'},
{id:'demo-3',name:'Montre classique',category:'Mode',description:'Montre au design intemporel.',price_fcfa:25000,stock:8,image_url:'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=900&q=80'}];
let products=[],category='';
const money=n=>new Intl.NumberFormat('fr-FR').format(Number(n)||0)+' FCFA';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const cart=()=>JSON.parse(localStorage.getItem('egonarCart')||'[]');
function count(){const e=document.getElementById('cart-count');if(e)e.textContent=cart().reduce((s,x)=>s+(Number(x.quantity)||0),0)}
async function load(){try{const r=await fetch(API+'/products');if(!r.ok)throw 0;const d=await r.json();products=(Array.isArray(d)?d:d.products||[]).map(p=>({id:p.id,name:p.name||p.nom,category:p.category||p.categorie||'',description:p.description||'',price_fcfa:Number(p.price_fcfa??p.prix??0),stock:Number(p.stock??0),image_url:p.image_url||p.image||''}));if(!products.length)products=DEMO}catch(e){products=DEMO}render()}
function render(){const box=document.getElementById('products-list');if(!box)return;let a=products.filter(p=>!category||p.category.toLowerCase()===category.toLowerCase());const q=(document.getElementById('search')?.value||'').trim().toLowerCase();if(q)a=a.filter(p=>`${p.name} ${p.category} ${p.description}`.toLowerCase().includes(q));const s=document.getElementById('sort')?.value;if(s==='priceAsc')a.sort((x,y)=>x.price_fcfa-y.price_fcfa);if(s==='priceDesc')a.sort((x,y)=>y.price_fcfa-x.price_fcfa);const c=document.getElementById('result-count');if(c)c.textContent=`${a.length} produit${a.length>1?'s':''}`;box.innerHTML=a.length?a.map(p=>`<article class="product"><div class="product-media">${p.image_url?`<img src="${esc(p.image_url)}" alt="${esc(p.name)}" loading="lazy">`:'<span class="product-placeholder">🛍️</span>'}</div><div class="product-info"><span class="product-category">${esc(p.category)}</span><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p><div class="price">${money(p.price_fcfa)}</div><button class="buy-btn" data-id="${esc(p.id)}">Ajouter au panier</button></div></article>`).join(''):'<div class="empty">Aucun produit trouvé. Essayez une autre recherche ou catégorie.</div>';box.querySelectorAll('.buy-btn').forEach(b=>b.onclick=()=>add(b.dataset.id));count()}
function add(id){const p=products.find(x=>String(x.id)===String(id));if(!p)return;const c=cart(),r=c.find(x=>String(x.product_id)===String(p.id));if(r){if(r.quantity>=p.stock)return alert('Stock maximum atteint.');r.quantity++}else c.push({product_id:p.id,name:p.name,price_fcfa:p.price_fcfa,image_url:p.image_url,quantity:1});localStorage.setItem('egonarCart',JSON.stringify(c));count();alert(`${p.name} a été ajouté au panier.`)}
function init(){count();document.getElementById('search-form')?.addEventListener('submit',e=>{e.preventDefault();render();document.getElementById('produits')?.scrollIntoView({behavior:'smooth'})});document.getElementById('search')?.addEventListener('input',render);document.getElementById('sort')?.addEventListener('change',render);document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{category=b.dataset.category||'';document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x===b));render()});document.getElementById('smart-form')?.addEventListener('submit',e=>{e.preventDefault();document.getElementById('search').value=document.getElementById('smart-search').value;render();document.getElementById('produits')?.scrollIntoView({behavior:'smooth'})});load()}
document.addEventListener('DOMContentLoaded',init);